{{- if .Values.externalSecrets.enabled -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "learnhouse.fullname" . }}-jwt-secret
  labels:
    {{- include "learnhouse.labels" . | nindent 4 }}
spec:
  length: 64
  digits: 20
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "learnhouse.fullname" . }}-secret
  labels:
    {{- include "learnhouse.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore | default "aws-secretsmanager" }}
    kind: ClusterSecretStore
  target:
    name: {{ include "learnhouse.fullname" . }}-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LEARNHOUSE_AUTH_JWT_SECRET_KEY: "{{ `{{ .jwtSecret }}` }}"
        NEXTAUTH_SECRET: "{{ `{{ .jwtSecret }}` }}"
        COLLAB_INTERNAL_KEY: "{{ `{{ .jwtSecret }}` }}"
        {{- if .Values.externalSecrets.remoteSecrets.dbPasswordKey }}
        LEARNHOUSE_SQL_CONNECTION_STRING: "postgresql://learnhouse:{{ `{{ .dbPassword }}` }}@postgres-postgresql.postgres.svc.cluster.local:5432/learnhouse"
        {{- end }}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "learnhouse.fullname" . }}-jwt-secret
      rewrite:
        - regexp:
            source: "(.*)"
            target: "jwtSecret"
{{- end }}
